// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AssetEdit: typeof import('./src/components/assetEdit.vue')['default']
    AssetsDisplay: typeof import('./src/components/assetsDisplay.vue')['default']
    AssetTypeEdit: typeof import('./src/components/assetTypeEdit.vue')['default']
    DepartmentEdit: typeof import('./src/components/departmentEdit.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FrontHeader: typeof import('./src/components/frontHeader.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    TableDetail: typeof import('./src/components/table-detail.vue')['default']
    TableEdit: typeof import('./src/components/table-edit.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
    UserTableDetail: typeof import('./src/components/userTableDetail.vue')['default']
    UserTableEdit: typeof import('./src/components/userTableEdit.vue')['default']
  }
}
